---
name: Functional tests (Remote)

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - "main"

permissions: {}

defaults:
  run:
    shell: sh

jobs:
  functional-tests-remote:
    name: Functional tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Run Pascal script
        uses: fabasoad/pascal-action@33e089a71e00c93ef3b93a9758f75e93cf8bf32f # main
        id: pascal
        with:
          path: ./HelloWorld.pas
      - name: Validate result
        env:
          PASCAL_RESULT: ${{ steps.pascal.outputs.result }}
        run: |
          [ "Hello World!" = "$PASCAL_RESULT" ] || exit 1;
