---
name: Security

on: # yamllint disable-line rule:truthy
  pull_request: {}
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-image:
    name: Build image
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      artifact-name: "${{ steps.artifact.outputs.name }}"
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Build image
        id: build-image
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        with:
          push: false
      - name: Save image
        id: artifact
        env:
          BUILD_IMAGE_DIGEST: ${{ steps.build-image.outputs.digest }}
        run: |
          artifact_name="$(date +%s)"
          archive_path="${RUNNER_TEMP}/${artifact_name}.tar"
          docker save --output "${archive_path}" "$BUILD_IMAGE_DIGEST"
          echo "path=${archive_path}" >> "$GITHUB_OUTPUT"
          echo "name=${artifact_name}" >> "$GITHUB_OUTPUT"
      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: "${{ steps.artifact.outputs.name }}"
          path: "${{ steps.artifact.outputs.path }}"
          retention-days: "1"
          compression-level: "0"
  sast:
    name: SAST
    needs: ["build-image"]
    permissions:
      contents: read
      security-events: write
    uses: fabasoad/reusable-workflows/.github/workflows/wf-security-sast.yml@e4ff663d3bc9ff9d225d2e967a0f94aad342d218 # main
    with:
      image: true
      image-artifact-name: "${{ needs.build-image.outputs.artifact-name }}"
